### ISSUE TITLE
READEME

### ISSUE THREAD

**Issue by Ashaba** [Kalela/BrightEvents#9]
I would recommend your readme aim at guiding your visitors on how to go about using the application.
 take an example from https://github.com/Ashaba/BucketList

**Comment by Kalela** [comment]
I've done some edits to the readme

**Comment by Ashaba** [comment]
Which branch are you working on? Because the readme is still not
informative (master and development) branches

**Comment by Kalela** [comment]
Working on ft-Better-UI-and-Logic-153324164.

**Comment by Kalela** [comment]
https://github.com/Kalela/BrightEvents/tree/ft-Better-UI-and-Logic-153324164
